// { Component } The de-structured component from React
import React, { Component } from 'react'
import Note from './Note'
import { FaPlus } from 'react-icons/fa'

class Board extends Component {

    constructor(props) {
        super(props);
        this.state = {
            notes : [
                {
                    id:0,
                    note:"Ring up Sachin"
                },
                {
                    id:1,
                    note:"Bring apples"
                }
            ]
        }

        this.add = this.add.bind(this)
        this.eachNote = this.eachNote.bind(this)
        this.update = this.update.bind(this)
        this.remove = this.remove.bind(this)
        this.nextId = this.nextId.bind(this)
    }

    /**
     * @desc Modifies the text inside the note
     * @param string newText and index value
     */
    update(newText, i){
        console.log ("Updating new text", i, newText)

        this.setState(prevState => ({
            notes: prevState.notes.map(
                note => (note.id !== i) ? note : {...note, note: newText}
            )
        }))
    }

    /**
     * @desc Adds new notes to the board
     * retains the existing notes and adds a new one.
     * The id is autogenerated using a custom-built function.
     * By default the text received from the button tag is null and "New Note"
     * @param string text
     */
    add(text){
        this.setState(prevState => ({
            notes: [
                ...prevState.notes,
                {
                    id: this.nextId(),
                    note:text
                }
            ]

        }))
    }

    /**
     * @desc Auto-generating ID for notes
     * @return incremented ID
     */
    nextId(){
        this.uniqueId = this.uniqueId || 0
        return this.uniqueId++
    }

    /**
     * @desc Deletes the note
     * Retains all the ids except for the argument passed
     * @param id
     */
    remove(id){
        console.log("removing item at id", id)
        this.setState(prevState => ({
            notes: prevState.notes.filter(note => note.id !== id)
        }))
    }

    /**
     * @desc This is the mapping function used for rendering 'Note' to the DOM.
     * @param id
     * @return <Note> elements with callbacks
     */
    eachNote(Note_temp, i){
        return (
            <Note key={i}
                  index={i}
                  onChange={this.update}
                  onRemove={this.remove}>
                {Note_temp.note}
            </Note>
        )
    }

    render() {
        return (
            <div className="board">

                {this.state.notes.map(this.eachNote)}

                <button onClick={this.add.bind(null,"New Note")}
                        id="add">
                    <FaPlus/>
                </button>
            </div>
        )
    }
}

export default Board
